credentials:
  usernames:
    dipika:
      email: me@mail.com
      name: Dipika Dhara
      password: $2b$12$b6KFtOtrS/JQQByRHGQFBO7saz7psV7OXrgB6nesddm6EIAQN2Gf2 #def
cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - me@mail.com